//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KhabibullinTRiZBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Disciplina
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Disciplina()
        {
            this.Uchebnaya_nagruzka = new HashSet<Uchebnaya_nagruzka>();
        }
    
        public int Kod_disciplini { get; set; }
        public int Kod_kafedry { get; set; }
        public string Nazvanie_disciplini { get; set; }
        public int Kl_chasov { get; set; }
        public string Tsikl_disciplini { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Uchebnaya_nagruzka> Uchebnaya_nagruzka { get; set; }
        public virtual Kafedra Kafedra { get; set; }
    }
}
