//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KhabibullinTRiZBD
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class InformationayaSystemaVUZAEntities : DbContext
    {
        private static InformationayaSystemaVUZAEntities _instance;
        public static InformationayaSystemaVUZAEntities getInstance()
        {
            if (_instance == null)
                _instance = new InformationayaSystemaVUZAEntities();
            return _instance;
        }
        public InformationayaSystemaVUZAEntities()
            : base("name=InformationayaSystemaVUZAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Disciplina> Disciplina { get; set; }
        public virtual DbSet<Fakultet> Fakultet { get; set; }
        public virtual DbSet<Kafedra> Kafedra { get; set; }
        public virtual DbSet<Prepodavatel> Prepodavatel { get; set; }
        public virtual DbSet<Uchebnaya_nagruzka> Uchebnaya_nagruzka { get; set; }
        public virtual DbSet<prepodsmall> prepodsmall { get; set; }
    }
}
