//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KhabibullinTRiZBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prepodavatel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Prepodavatel()
        {
            this.Uchebnaya_nagruzka = new HashSet<Uchebnaya_nagruzka>();
        }
    
        public int Kod_prepod { get; set; }
        public int Kod_kafedry { get; set; }
        public string Lastname { get; set; }
        public string Firstname { get; set; }
        public string Patronymic { get; set; }
        public int God_post { get; set; }
        public int Stazh { get; set; }
        public string Dolzhnost { get; set; }
        public string Photo { get; set; }
        public Nullable<System.DateTime> Date_rozhd { get; set; }
        public string GetFIO
        {
            get
            {
                return $"{Lastname} {Firstname} {Patronymic}";
            }
        }
        public string GetKafedra
        {
            get
            {
                return Kafedra.Nazvanie_kaf;
            }
        }
        public string GetNumKorpus
        {
            get
            {
                return $"{Kafedra.N_korpusa}к. {Kafedra.N_komnaty} каб.";
            }
        }
        public string GetDateBirth
        {
            get
            {
                return $"{Date_rozhd?.Day}/{Date_rozhd?.Month}/{Date_rozhd?.Year}";
            }
        }
        public virtual Kafedra Kafedra { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Uchebnaya_nagruzka> Uchebnaya_nagruzka { get; set; }
    }
}
