//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KhabibullinTRiZBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Uchebnaya_nagruzka
    {
        public int Kod_nagruzki { get; set; }
        public int Kod_prepod { get; set; }
        public int Kod_disciplini { get; set; }
        public string Ucheb_god { get; set; }
        public int Semestr { get; set; }
        public string Gruppy { get; set; }
        public int Kol_student { get; set; }
        public string Itog_kontrol { get; set; }
    
        public virtual Disciplina Disciplina { get; set; }
        public virtual Prepodavatel Prepodavatel { get; set; }
    }
}
